/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Source: docs/curriculum/montana-math-standards-2026-CASE.csv
 * Script: scripts/build-standards.mjs
 * Regenerate: npm run build:standards
 *
 * The Montana Mathematics Content Standards (2026) for grades 4 and 5,
 * parsed from the CASE export at build time so nothing has to parse CSV in
 * the browser. Edit the CSV or the script, then regenerate — hand edits here
 * are lost on the next run.
 */

export type DomainCode = 'OA' | 'NBT' | 'NF' | 'MD' | 'G'
export type CardStat = 'PAC' | 'SHO' | 'PAS' | 'DRI' | 'DEF' | 'PHY'

export interface Standard {
  /** Montana code, e.g. `MT.4.NF.3`. */
  id: string
  grade: 4 | 5
  domain: DomainCode
  /** Verbatim `Full Statement`, including any `*...*` emphasis. */
  statement: string
  itemType: 'Standard' | 'Component'
  /** Components only: the id of the standard they sit under. */
  parentId?: string
}

export const STANDARDS: Standard[] = [
  {
    id: 'MT.4.OA.1',
    grade: 4,
    domain: 'OA',
    statement: 'Interpret a multiplication equation as a multiplicative comparison, and represent verbal statements of multiplicative comparisons as multiplication equations.',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.OA.2',
    grade: 4,
    domain: 'OA',
    statement: 'Multiply or divide to solve problems in context that involve multiplicative comparison and distinguish multiplicative comparison from additive comparison.',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.OA.3',
    grade: 4,
    domain: 'OA',
    statement: 'Solve multistep problems in context with whole numbers and having whole-number answers using the four operations, including problems in which remainders must be interpreted, represent these problems using equations with a letter standing for the unknown quantity, and assess the reasonableness of answers using mental computation and estimation strategies. This standard should incorporate cultural context relating to Montana Indigenous Peoples and local communities.',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.OA.4',
    grade: 4,
    domain: 'OA',
    statement: 'Find all factor pairs for a whole number in the range 1-100, recognize that a whole number is a multiple of each of its factors, determine whether a given whole number in the range 1-1000 is a multiple of a given one-digit number, and determine whether a given whole number in the range 1-100 is prime or composite.',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.OA.5',
    grade: 4,
    domain: 'OA',
    statement: 'Analyze a number or shape pattern that follows a given rule, identify and explain informally features of the pattern that were not explicit in the rule itself, generate terms in the resulting sequence, and observe the pattern.',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.NBT.1',
    grade: 4,
    domain: 'NBT',
    statement: 'Recognize that in a multi-digit whole number, each place represents ten times the place to its right.',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.NBT.2',
    grade: 4,
    domain: 'NBT',
    statement: 'Read and write multi-digit whole numbers using standard form, word form, and expanded form and compare two multi-digit numbers based on the value of the digits in each place using >, =, and < symbols.',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.NBT.3',
    grade: 4,
    domain: 'NBT',
    statement: 'Use place value understanding to round multi-digit whole numbers to any place.',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.NBT.4',
    grade: 4,
    domain: 'NBT',
    statement: 'Accurately and efficiently add and subtract multi-digit whole numbers using the standard algorithm.',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.NBT.5',
    grade: 4,
    domain: 'NBT',
    statement: 'Multiply a whole number of up to four digits by a one-digit whole number, multiply two two-digit numbers, flexibly using strategies based on place value and the properties of operations, and illustrate and explain the calculation by using equations, rectangular arrays, and/or area models.',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.NBT.6',
    grade: 4,
    domain: 'NBT',
    statement: 'Find whole-number quotients and remainders with up to four-digit dividends and one-digit divisors, flexibly using strategies based on place value, the properties of operations, and/or the relationship between multiplication and division, and illustrate and explain the calculation by using equations, rectangular arrays, and/or area models.',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.NF.1',
    grade: 4,
    domain: 'NF',
    statement: 'Explain why a fraction a/b is equivalent to a fraction (n × a)/(n × b) by using visual fraction models and use this principle to recognize and generate equivalent fractions.',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.NF.2',
    grade: 4,
    domain: 'NF',
    statement: 'Compare two fractions with different numerators and different denominators by creating common denominators or numerators, or by comparing to a benchmark fraction, recognize that comparisons are valid only when the two fractions refer to the same whole, record the results of comparisons with symbols >, =, or <, and justify the conclusions.',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.NF.3',
    grade: 4,
    domain: 'NF',
    statement: 'Understand a fraction a/b with a > 1 as a sum of fractions 1/b by:',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.NF.3.a',
    grade: 4,
    domain: 'NF',
    statement: '*Understand a fraction a/b with a > 1 as a sum of fractions 1/b by* understanding addition and subtraction of fractions as joining and separating parts referring to the same whole.',
    itemType: 'Component',
    parentId: 'MT.4.NF.3',
  },
  {
    id: 'MT.4.NF.3.b',
    grade: 4,
    domain: 'NF',
    statement: '*Understand a fraction a/b with a > 1 as a sum of fractions 1/b by* decomposing a fraction into a sum of fractions with the same denominator in more than one way, recording each decomposition by an equation.',
    itemType: 'Component',
    parentId: 'MT.4.NF.3',
  },
  {
    id: 'MT.4.NF.3.c',
    grade: 4,
    domain: 'NF',
    statement: '*Understand a fraction a/b with a > 1 as a sum of fractions 1/b by* adding and subtracting mixed numbers with like denominators by replacing each mixed number with an equivalent improper fraction or other efficient strategies.',
    itemType: 'Component',
    parentId: 'MT.4.NF.3',
  },
  {
    id: 'MT.4.NF.3.d',
    grade: 4,
    domain: 'NF',
    statement: '*Understand a fraction a/b with a > 1 as a sum of fractions 1/b by* solving problems in context that involve addition and subtraction of fractions referring to the same whole or having like denominators. This standard should incorporate cultural context relating to Montana Indigenous Peoples and local communities.',
    itemType: 'Component',
    parentId: 'MT.4.NF.3',
  },
  {
    id: 'MT.4.NF.4',
    grade: 4,
    domain: 'NF',
    statement: 'Apply and extend previous understandings of multiplication to multiply a fraction by a whole number by:',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.NF.4.a',
    grade: 4,
    domain: 'NF',
    statement: '*Apply and extend previous understandings of multiplication to multiply a fraction by a whole number by* understanding a fraction a/b as a multiple of 1/b and recording the conclusion by the equation a/b = a*(1/b).',
    itemType: 'Component',
    parentId: 'MT.4.NF.4',
  },
  {
    id: 'MT.4.NF.4.b',
    grade: 4,
    domain: 'NF',
    statement: '*Apply and extend previous understandings of multiplication to multiply a fraction by a whole number by* understanding a multiple of a/b as a multiple of 1/b, using this to multiply a fraction by a whole number and recognizing n × (a/b) = (n × a)/b).',
    itemType: 'Component',
    parentId: 'MT.4.NF.4',
  },
  {
    id: 'MT.4.NF.4.c',
    grade: 4,
    domain: 'NF',
    statement: '*Apply and extend previous understandings of multiplication to multiply a fraction by a whole number by* solving problems in context involving multiplication of a fraction by a whole number. This standard should incorporate cultural context relating to Montana Indigenous Peoples and local communities.',
    itemType: 'Component',
    parentId: 'MT.4.NF.4',
  },
  {
    id: 'MT.4.NF.5',
    grade: 4,
    domain: 'NF',
    statement: 'Express a fraction with denominator 10 as an equivalent fraction with denominator 100, and use this technique to add two fractions with respective denominators 10 and 100.',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.NF.6',
    grade: 4,
    domain: 'NF',
    statement: 'Use decimal notation for fractions with denominators 10 or 100.',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.NF.7',
    grade: 4,
    domain: 'NF',
    statement: 'Compare two decimals to hundredths by reasoning about their size, recognize that comparisons are valid only when the two decimals refer to the same whole, record the results of comparisons with the symbols >, =, or <, and justify the conclusions.',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.MD.1',
    grade: 4,
    domain: 'MD',
    statement: 'Know relative sizes of units within one system of measurement and within the system, express measurements of a larger unit in terms of a smaller unit.',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.MD.2',
    grade: 4,
    domain: 'MD',
    statement: 'Use the four operations to solve problems in context using distances, intervals of time, liquid volumes, masses of objects, and money, including problems with simple fractions or decimals and problems that require expressing measurements given in a larger unit in terms of a smaller unit, and represent measurement quantities using diagrams that feature a measurement scale. This standard should incorporate cultural context relating to Montana Indigenous Peoples and local communities.',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.MD.3',
    grade: 4,
    domain: 'MD',
    statement: 'Apply the area and perimeter formulas for rectangles including problems in context.',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.MD.4',
    grade: 4,
    domain: 'MD',
    statement: 'Make a line plot to display a data set of measurements in fractions of a unit and solve problems involving addition and subtraction of fractions by using information presented in line plots.',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.MD.5',
    grade: 4,
    domain: 'MD',
    statement: 'Recognize angles as geometric shapes that are formed wherever two rays share a common endpoint and understand concepts of angle measurement by:',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.MD.5.a',
    grade: 4,
    domain: 'MD',
    statement: '*Recognize angles as geometric shapes that are formed wherever two rays share a common endpoint and understand concepts of angle measurement by* understanding that an angle is formed by two rays with a common endpoint at the center of a circle that measures a total of 360 degrees, and a single-degree unit measure is equal to 1/360th of the circle, and',
    itemType: 'Component',
    parentId: 'MT.4.MD.5',
  },
  {
    id: 'MT.4.MD.5.b',
    grade: 4,
    domain: 'MD',
    statement: '*Recognize angles as geometric shapes that are formed wherever two rays share a common endpoint and understand concepts of angle measurement by* understanding that an angle that turns through n one-degree angles is said to have an angle measure of n degrees.',
    itemType: 'Component',
    parentId: 'MT.4.MD.5',
  },
  {
    id: 'MT.4.MD.6',
    grade: 4,
    domain: 'MD',
    statement: 'Measure angles in whole-number degrees using a protractor and sketch angles of specified measure.',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.MD.7',
    grade: 4,
    domain: 'MD',
    statement: 'Recognize angle measure as additive. When an angle is decomposed into nonoverlapping parts, the angle measure of the whole is the sum of the angle measures of the parts. Solve addition and subtraction problems to find unknown angles on a diagram including problems in context.',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.G.1',
    grade: 4,
    domain: 'G',
    statement: 'Draw points, lines, line segments, rays, angles (right, acute, obtuse), and perpendicular and parallel lines and identify these in two-dimensional figures.',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.G.2',
    grade: 4,
    domain: 'G',
    statement: 'Classify two-dimensional figures based on the presence or absence of parallel or perpendicular lines or the presence or absence of angles of a specified size, recognize right triangles as a category, and identify right triangles.',
    itemType: 'Standard',
  },
  {
    id: 'MT.4.G.3',
    grade: 4,
    domain: 'G',
    statement: 'Recognize a line of symmetry for a two-dimensional figure as a line across the figure such that the figure can be folded along the line into matching parts, identify line-symmetric figures, and draw lines of symmetry. This standard should incorporate designs and cultural context relating to Montana Indigenous Peoples and local communities.',
    itemType: 'Standard',
  },
  {
    id: 'MT.5.OA.1',
    grade: 5,
    domain: 'OA',
    statement: 'Use parentheses, brackets, or braces in numerical expressions and evaluate expressions with these symbols using the order of operations.',
    itemType: 'Standard',
  },
  {
    id: 'MT.5.OA.2',
    grade: 5,
    domain: 'OA',
    statement: 'Write simple expressions that record calculations with numbers and interpret numerical expressions without evaluating them.',
    itemType: 'Standard',
  },
  {
    id: 'MT.5.OA.3',
    grade: 5,
    domain: 'OA',
    statement: 'Generate two numerical patterns using given rules and complete an input-output table for the data, identify apparent relationships between corresponding terms, form ordered pairs from the values in the input-output table, and graph them on a coordinate plane.',
    itemType: 'Standard',
  },
  {
    id: 'MT.5.NBT.1',
    grade: 5,
    domain: 'NBT',
    statement: 'Recognize that in a multi-digit number, a digit in one place represents 10 times as much as it represents in the place to its right and 1/10 of what it represents in the place to its left.',
    itemType: 'Standard',
  },
  {
    id: 'MT.5.NBT.2',
    grade: 5,
    domain: 'NBT',
    statement: 'Explain patterns in the number of zeros of the product when multiplying a number by powers of 10, explain patterns in the placement of the decimal point when a decimal is multiplied or divided by a power of 10, and use whole-number exponents to denote powers of 10.',
    itemType: 'Standard',
  },
  {
    id: 'MT.5.NBT.3',
    grade: 5,
    domain: 'NBT',
    statement: 'Read, write, and compare decimals to thousandths by:',
    itemType: 'Standard',
  },
  {
    id: 'MT.5.NBT.3.a',
    grade: 5,
    domain: 'NBT',
    statement: '*Read, write, and compare decimals to thousandths by* reading and writing decimals to thousandths using standard form, word form, and expanded form.',
    itemType: 'Component',
    parentId: 'MT.5.NBT.3',
  },
  {
    id: 'MT.5.NBT.3.b',
    grade: 5,
    domain: 'NBT',
    statement: '*Read, write, and compare decimals to thousandths by* comparing two decimals to thousandths based on meanings of the digits in each place using >, =, and < symbols.',
    itemType: 'Component',
    parentId: 'MT.5.NBT.3',
  },
  {
    id: 'MT.5.NBT.4',
    grade: 5,
    domain: 'NBT',
    statement: 'Use place value understandings to round decimals to any place.',
    itemType: 'Standard',
  },
  {
    id: 'MT.5.NBT.5',
    grade: 5,
    domain: 'NBT',
    statement: 'Accurately and efficiently multiply multi-digit whole numbers using the standard algorithm.',
    itemType: 'Standard',
  },
  {
    id: 'MT.5.NBT.6',
    grade: 5,
    domain: 'NBT',
    statement: 'Flexibly, accurately, and efficiently find whole-number quotients of whole numbers with up to four-digit dividends and two-digit divisors using strategies based on place value, the properties of operations, and/or the relationship between multiplication and division and illustrate and explain the calculation by using equations, rectangular arrays, and/or area models.',
    itemType: 'Standard',
  },
  {
    id: 'MT.5.NBT.7',
    grade: 5,
    domain: 'NBT',
    statement: 'Add, subtract, multiply, and divide decimals to hundredths using concrete models or drawings. This standard should incorporate designs and cultural context relating to Montana Indigenous Peoples and local communities.',
    itemType: 'Standard',
  },
  {
    id: 'MT.5.NF.1',
    grade: 5,
    domain: 'NF',
    statement: 'Add and subtract fractions with unlike denominators (including mixed numbers) by replacing given fractions with equivalent fractions.',
    itemType: 'Standard',
  },
  {
    id: 'MT.5.NF.2',
    grade: 5,
    domain: 'NF',
    statement: 'Solve problems in context that involve addition and subtraction of fractions referring to the same whole, including cases of unlike denominators, and use benchmark fractions and number sense of fractions to estimate mentally and assess the reasonableness of answers.',
    itemType: 'Standard',
  },
  {
    id: 'MT.5.NF.3',
    grade: 5,
    domain: 'NF',
    statement: 'Interpret a fraction as division of the numerator by the denominator (a/b = a ÷ b) and solve problems in context that involve division of whole numbers leading to answers in the form of fractions or mixed numbers.',
    itemType: 'Standard',
  },
  {
    id: 'MT.5.NF.4',
    grade: 5,
    domain: 'NF',
    statement: 'Apply and extend previous understandings of multiplication to multiply a fraction or whole number by a fraction by:',
    itemType: 'Standard',
  },
  {
    id: 'MT.5.NF.4.a',
    grade: 5,
    domain: 'NF',
    statement: '*Apply and extend previous understandings of multiplication to multiply a fraction or whole number by a fraction by* expressing the product (a/b) × q as "a" parts of a partition of q into b equal parts, equivalently, as the result of a sequence of operations a × q ÷ b.',
    itemType: 'Component',
    parentId: 'MT.5.NF.4',
  },
  {
    id: 'MT.5.NF.4.b',
    grade: 5,
    domain: 'NF',
    statement: '*Apply and extend previous understandings of multiplication to multiply a fraction or whole number by a fraction by* finding the area of a rectangle with fractional side lengths by tiling it with unit squares of the appropriate unit fraction side lengths, showing that the area is the same as would be found by multiplying the side lengths, multiplying fractional side lengths to find areas of rectangles, and represent representing fraction products as rectangular areas.',
    itemType: 'Component',
    parentId: 'MT.5.NF.4',
  },
  {
    id: 'MT.5.NF.5',
    grade: 5,
    domain: 'NF',
    statement: 'Interpret multiplication as scaling (resizing), by:',
    itemType: 'Standard',
  },
  {
    id: 'MT.5.NF.5.a',
    grade: 5,
    domain: 'NF',
    statement: '*Interpret multiplication as scaling (resizing), by* comparing the size of a product to the size of one factor on the basis of the size of the other factor without performing the indicated multiplication.',
    itemType: 'Component',
    parentId: 'MT.5.NF.5',
  },
  {
    id: 'MT.5.NF.5.b',
    grade: 5,
    domain: 'NF',
    statement: '*Interpret multiplication as scaling (resizing), by* explaining why multiplying a given number by a fraction greater than 1 results in a product greater than the given number explaining why multiplying a given number by a fraction less than 1 results in a product smaller than the given number, and relating the principle of fraction equivalence a/b = (n × a)/(n × b) to the effect of multiplying a/b by 1.',
    itemType: 'Component',
    parentId: 'MT.5.NF.5',
  },
  {
    id: 'MT.5.NF.6',
    grade: 5,
    domain: 'NF',
    statement: 'Solve problems in context that involve multiplication of fractions and mixed numbers. This standard should incorporate cultural context relating to Montana Indigenous Peoples and local communities.',
    itemType: 'Standard',
  },
  {
    id: 'MT.5.NF.7',
    grade: 5,
    domain: 'NF',
    statement: 'Apply and extend previous understandings of division to divide unit fractions by whole numbers and whole numbers by unit fractions by:',
    itemType: 'Standard',
  },
  {
    id: 'MT.5.NF.7.a',
    grade: 5,
    domain: 'NF',
    statement: '*Apply and extend previous understandings of division to divide unit fractions by whole numbers and whole numbers by unit fractions by* expressing division of a unit fraction by a nonzero whole number and computing such quotients.',
    itemType: 'Component',
    parentId: 'MT.5.NF.7',
  },
  {
    id: 'MT.5.NF.7.b',
    grade: 5,
    domain: 'NF',
    statement: '*Apply and extend previous understandings of division to divide unit fractions by whole numbers and whole numbers by unit fractions by* expressing division of a whole number by a unit fraction and computing such quotients.',
    itemType: 'Component',
    parentId: 'MT.5.NF.7',
  },
  {
    id: 'MT.5.NF.7.c',
    grade: 5,
    domain: 'NF',
    statement: '*Apply and extend previous understandings of division to divide unit fractions by whole numbers and whole numbers by unit fractions by:* solve problems in context involving division of unit fractions by nonzero whole numbers and division of whole numbers by unit fractions. This standard should incorporate cultural context relating to Montana Indigenous Peoples and local communities.',
    itemType: 'Component',
    parentId: 'MT.5.NF.7',
  },
  {
    id: 'MT.5.MD.1',
    grade: 5,
    domain: 'MD',
    statement: 'Convert among different-sized standard measurement units within a given measurement system and use these conversions in solving multi-step problems in context. This standard should incorporate cultural context relating to Montana Indigenous Peoples and local communities.',
    itemType: 'Standard',
  },
  {
    id: 'MT.5.MD.2',
    grade: 5,
    domain: 'MD',
    statement: 'Make a line plot to display a data set of measurements in fractions of a unit and use operations on fractions to solve problems involving information presented in line plots.',
    itemType: 'Standard',
  },
  {
    id: 'MT.5.MD.3',
    grade: 5,
    domain: 'MD',
    statement: 'Recognize volume as an attribute of solid figures and understand concepts of volume measurement by:',
    itemType: 'Standard',
  },
  {
    id: 'MT.5.MD.3.a',
    grade: 5,
    domain: 'MD',
    statement: '*Recognize volume as an attribute of solid figures and understand concepts of volume measurement by* understanding that a cube with side length 1 unit, called a "unit cube," is said to have "one cubic unit" of volume and can be used to measure volume.',
    itemType: 'Component',
    parentId: 'MT.5.MD.3',
  },
  {
    id: 'MT.5.MD.3.b',
    grade: 5,
    domain: 'MD',
    statement: '*Recognize volume as an attribute of solid figures and understand concepts of volume measurement by* understanding that a solid figure which can be packed without gaps or overlaps using n unit cubes is said to have a volume of n cubic units.',
    itemType: 'Component',
    parentId: 'MT.5.MD.3',
  },
  {
    id: 'MT.5.MD.4',
    grade: 5,
    domain: 'MD',
    statement: 'Measure volumes by counting unit cubes, using cubic cm, cubic in, cubic ft, and non-standard units.',
    itemType: 'Standard',
  },
  {
    id: 'MT.5.MD.5',
    grade: 5,
    domain: 'MD',
    statement: 'Relate volume to the operations of multiplication and addition and volume problems including problems in context by:',
    itemType: 'Standard',
  },
  {
    id: 'MT.5.MD.5.a',
    grade: 5,
    domain: 'MD',
    statement: '*Relate volume to the operations of multiplication and addition and volume problems including problems in context by* finding the volume of a right rectangular prism with whole-number side lengths by packing it with unit cubes and showing that the volume is the same as would be found by multiplying the edge lengths, equivalently by multiplying the height by the area of the base and representing the product of three whole numbers using the associative property of multiplication.',
    itemType: 'Component',
    parentId: 'MT.5.MD.5',
  },
  {
    id: 'MT.5.MD.5.b',
    grade: 5,
    domain: 'MD',
    statement: '*Relate volume to the operations of multiplication and addition and volume problems including problems in context by* applying the formulas V = l × w × h and V = B × h for rectangular prisms to find volumes of right rectangular prisms with whole-number edge lengths including problems in context.',
    itemType: 'Component',
    parentId: 'MT.5.MD.5',
  },
  {
    id: 'MT.5.MD.5.c',
    grade: 5,
    domain: 'MD',
    statement: '*Relate volume to the operations of multiplication and addition and volume problems including problems in context by* recognizing volume as additive and finding volumes of solid figures composed of two nonoverlapping right rectangular prisms by adding the volumes of the nonoverlapping parts, applying this technique to solve problems in context. This standard should incorporate cultural context relating to Montana Indigenous Peoples and local communities.',
    itemType: 'Component',
    parentId: 'MT.5.MD.5',
  },
  {
    id: 'MT.5.G.1',
    grade: 5,
    domain: 'G',
    statement: 'Use a pair of perpendicular number lines, called axes, to define a coordinate system with the intersection of the lines at the origin arranged to coincide with the 0 on each line and a given point in the plane located by using an ordered pair of numbers, called its coordinates. Understand that the x-coordinate, the first number, indicates how far to travel from the origin in the direction of the x-axis and the y-coordinate, the second number, indicates how far to travel in the direction of the y-axis.',
    itemType: 'Standard',
  },
  {
    id: 'MT.5.G.2',
    grade: 5,
    domain: 'G',
    statement: 'Represent problems including problems in context by graphing points in the first quadrant of the coordinate plane and interpret coordinate values of points in the context of the situation. This standard should incorporate designs and cultural context relating to Montana Indigenous Peoples and local communities.',
    itemType: 'Standard',
  },
  {
    id: 'MT.5.G.3',
    grade: 5,
    domain: 'G',
    statement: 'Understand that attributes belonging to a category of two-dimensional figures also belong to all subcategories of that category.',
    itemType: 'Standard',
  },
  {
    id: 'MT.5.G.4',
    grade: 5,
    domain: 'G',
    statement: 'Classify two-dimensional figures in a hierarchy based on properties.',
    itemType: 'Standard',
  },
]

/**
 * Each domain drives one stat on the player card. The sixth stat, PAC, is
 * fluency — speed rather than any single domain — so nothing maps to it.
 */
export const DOMAIN_TO_STAT: Record<DomainCode, CardStat> = {
  OA: 'PAS',
  NBT: 'DEF',
  NF: 'DRI',
  MD: 'PHY',
  G: 'SHO',
}

/** Built once here so downstream modules can look up by id without rebuilding it. */
export const STANDARDS_BY_ID: Record<string, Standard> = Object.fromEntries(
  STANDARDS.map((s) => [s.id, s]),
)
